version: "3"
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: terra_user
      MYSQL_PASSWORD: terra_password
      MYSQL_ROOT_PASSWORD: terra_password
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: terra_user
      WORDPRESS_DB_PASSWORD: terra_password
      WORDPRESS_DB_NAME: db
    volumes:
      - ./:/var/www/html
volumes:
  mysql: {}